name: api_app_deploy_test
services:
  api_app_deploy_test:
    container_name: api_app_deploy_test
    build:
      context: .
      dockerfile: Dockerfile.prod
      args:
        NODE_VERSION: 22.12.0
    env_file:
      - .env
    environment:
      NODE_ENV: dev
    ports:
      - ${APP_PORT}:${APP_PORT}
    restart: unless-stopped
    command: npm run start
